name: kWLK
version: ${version}
main: com.kanorto.kwlk.KWLKPlugin
description: ${description}
api-version: '1.21'
author: Kanorto

commands:
  kwlk:
    description: Kick all players without permission
    usage: /kwlk
    permission: kwlk.use
    
permissions:
  kwlk.use:
    description: Allows use of the kick command and exempts from being kicked
    default: op
  kwlk.bypass:
    description: Exempts player from being kicked and auto-adds to whitelist
    default: op
